name: bambiki-dev

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./conf/postgres/multiple-db.sh:/docker-entrypoint-initdb.d/multiple-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_MULTIPLE_DATABASES=bambiki
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 3